name: portfolio
services:
    portfolio-client:
        container_name: portfolio-client-production
        image: affinity/portfolio-client:production
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '8000:3000'
        environment:
            - NODE_ENV=production
            - NEXT_TELEMETRY_DISABLED=1
        restart: unless-stopped
        networks:
            - portfolio-network-production

networks:
    portfolio-network-production:
        driver: bridge
