name: techfolio
services:
    techfolio-client:
        container_name: techfolio-client
        image: affinity/techfolio-client
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '8000:3000'
        environment:
            - NODE_ENV=production
            - NEXT_TELEMETRY_DISABLED=1
        restart: unless-stopped
        networks:
            - techfolio-network

networks:
    techfolio-network:
        driver: bridge
