name: Deploy to Firebase Hosting

on:
    push:
        branches:
            - main
    pull_request:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup PNPM
              uses: pnpm/action-setup@v4
              with:
                  version: 10.11.0
                  run_install: true

            - name: Build Project
              run: pnpm run build

            - name: Upload Built Site
              uses: actions/upload-artifact@v4
              with:
                  name: site
                  path: apps/client/out

    deploy:
        needs: build
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        runs-on: ubuntu-latest

        steps:
            - name: Download Built Site
              uses: actions/download-artifact@v4
              with:
                  name: site
                  path: apps/client/out

            - name: Deploy to Firebase Hosting (Live)
              uses: FirebaseExtended/action-hosting-deploy@v0
              with:
                  repoToken: ${{ secrets.GITHUB_TOKEN }}
                  firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
                  channelId: live
                  projectId: techfolio-5c7d5
                  entryPoint: ./Techfolio.Client

    preview:
        needs: build
        if: github.event_name == 'pull_request'
        runs-on: ubuntu-latest

        steps:
            - name: Download built site
              uses: actions/download-artifact@v4
              with:
                  name: site
                  path: apps/client/out

            - name: Deploy to Firebase Hosting (Preview)
              uses: FirebaseExtended/action-hosting-deploy@v0
              with:
                  repoToken: ${{ secrets.GITHUB_TOKEN }}
                  firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
                  projectId: techfolio-5c7d5
                  channelId: pr-${{ github.event.number }}
                  expires: 7d
                  entryPoint: ./Techfolio.Client
