name: CI/CD Workflow Pipeline

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Setup Turborepo cache
        uses: actions/cache@v3
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Clean install
        run: |
          pnpm clean || true
          rm -rf node_modules || true
          rm -rf packages/*/node_modules || true
          rm -rf apps/*/node_modules || true
          pnpm install --no-frozen-lockfile

      - name: Build packages
        run: pnpm run build --filter="./packages/*"

      - name: Build apps
        run: pnpm run build

      - name: Test
        run: pnpm run test --if-present

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main')

    steps:
      - name: SSH and Deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            cd ${{ secrets.REPOSITORY_DIRECTORY }}
            git pull ${{ secrets.REPOSITORY_SSH }}

            echo "Environmental Setup for Dockerizing Container"
            docker-compose -f docker-compose.yml down
            docker-compose -f docker-compose.yml build --no-cache
            docker-compose -f docker-compose.yml up -d
            
            echo "Refactoring and Cleanup for Docker Resources"
            docker image prune -af --filter "until=24h"
            docker system prune -f --volumes